events {}

http {

    upstream auth {
        server auth-service:8080;
    }

    upstream order {
        server order-service:8080;
    }

    upstream inventory {
        server inventory-service:8080;
    }

    server {
        listen 80;
        server_name mymicroservices.duckdns.org;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://auth;
        }
    }

}